# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  lc-dev1.co.uk:
    site_hosts:
      - canonical: lc-blogs-trellis.local
        redirects:
          - www.llc-blogs-trellis.local
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@lc-blogs-trellis.local
    site_title: Leicester College Blogs
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false