# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: Bk66Tzi50FGGyXXAR9UsOMZIJyp96Zo41XtsJl92hNxgq8SHmk

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: 138yRY8LcZ9F0Q38k27565r675KURE1B40naEN37Y84t5vcx3a
    salt: "zEC7GD_1mbjn}fAg2vw&kwc|Bo{l0rZ|hzD[_Xc^F6YR6qU{Y%RD}Uq+C{9j!Bf8"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
#template error while templating string: Missing end of comment tag
vault_wordpress_sites:
  leicestercollegeblog.co.uk:
    env:
      db_password: vh27052pRCQ3W0Jbxn9g7nIm7270S25m2e499I516oU3H99uyZ
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "XHP2V{g[+(r4#vjKDl=o<qwFlBTsg*&V,:K.eURZ3yzqui]VPvWh*a(<Vz}8Pjw!"
      secure_auth_key: "rLzT&^z=FL8Rw]gH7MI>r4&M/6ma29XeO?&|BYrPr)3F)EjSNG8vmvbP^B.N2TMN"
      logged_in_key: "p:]Q8[=pAVPZZ0C$e=B${HPR`.P1z8/]c+&#?G=C8b7AceXWG_hSAdN>7o8kEjO@"
      nonce_key: "lJAxy-b}xF.^8aBY:V:2>cO<RestPo6bcCQCgyG8W.cP]TF}@do5l_@I3mES}*C("
      auth_salt: "@0+0E8V^U*]<o$J&>MY/60G||nR->,(%;#W}gI.t}76,zai(T}$eKld2+0.VU`n&"
      secure_auth_salt: "!x*wJ/%%,B[r_#5nF,|O?4v]d+[0;34sV4{-h[TOFnefCgz|SvO,Z[3O>`B[N_`Z"
      logged_in_salt: "G>Z1l^*plm5j0L7Cfp{xDdN/z2ea#y]kTvs}[#>-Vq7rebR]YV>&VKcVj=R(]3l>"
      nonce_salt: "vlA=/ewI7rDd)dF}?sE{0S/r{,Ku3^bbvk}!2P>../5#ECAw%F.;YK>(ttY}5qCG"